name: Lint

on:
  push:
    branches:
      # - main
      - dev
      - test/*
      - actions/*
  pull_request:
    branches:
      - dev
      - test/*
      - actions/*

jobs:
  eslint-prettier-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.4.0

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint

      - name: Check Formatting
        run: pnpm prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,scss,md}"
